"""empty message

Revision ID: 495713dab0aa
Revises: 5c5ff2150a3f
Create Date: 2024-01-30 11:50:42.095064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495713dab0aa'
down_revision = '5c5ff2150a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('artist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'Venue', ['venue_id'], ['id'])
        batch_op.create_foreign_key(None, 'Artist', ['artist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('artist_id')
        batch_op.drop_column('venue_id')

    # ### end Alembic commands ###
